name: Axhole
favicon: null
layout_spectrum: 0.5656516302842647
typography_spectrum: 0.12672760896384716
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7898249600548297
  lightness: 0.2367651069071144
  saturation: 0.451118144672364
  rhythmicContrast: 0.21439363854005933
purpose: []
